# Dependencies
markdown:            redcarpet
redcarpet:
  extensions:        [footnotes]
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               KC Sivaramakrishnan
tagline:             'Research Associate @ OCaml Labs'
description:         'KC Sivaramakrishnan'
url:                 http://kcsrk.info
baseurl:             /
paginate:            5
paginate_path:       blog/page:num
excerpt_separator:   ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed

# About/contact
author:
  name:              KC Sivaramakrishnan
  url:               https://twitter.com/kc_srk
  email:             sk826@cl.cam.ac.uk

# Custom vars
version:             1.0.0
